# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.locale_listener:
            class: Proethos2\CoreBundle\EventListener\LocaleListener
            arguments: ["%kernel.default_locale%"]
            tags:
                - { name: kernel.event_subscriber }

    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension